### ISSUE TITLE
IMPORTANT: Contact this Job Seeker  & Contact this Recruiter: no reply back options

### ISSUE THREAD

**Issue by achille005** [achille005/JobApp#19]
These emails don't have reply to JS or to R option
If this is not possible, we have to include in the email body:

Job Seeker Email: jobseeker@email.com
Phone: Job Seeker Phone #

Same for Recruiter:
...
...

NOTE: cronJobs Emails should be no-reply

**Comment by Astrea123** [comment]
It is not clear to me . Please elaborate your point

**Comment by achille005** [comment]
I believe you said, the app is send this email via sendgrid that is why we can't have Reply back email address. Correct? If so Recruiter and JS have to have no way to conversate. That is why i am saying to:
include the following in the email:
Job Seeker Email: jobseeker@email.com
Phone: Job Seeker Phone #

**Comment by Astrea123** [comment]
This issue is conflict with issue  #27 .Please let me know Should I do this .If we will send jobseeker email address  onclicking the "Contact this recruiter " button then Recruiter will contact to the JobSeeker without paying.

**Comment by achille005** [comment]
I agree. Let's close this one. #27 to keep - Thank you for pointing this out
