### ISSUE TITLE
Remove  heroku says - just show the actual error message

### ISSUE THREAD

**Issue by achille005** [achille005/JobApp#29]
This is applied to all error messages:

![remove "herokuapp.herokuapp.com says" - just show the actual error message](https://cloud.githubusercontent.com/assets/6147947/26039186/9a65603e-38e5-11e7-9997-a4c066c0ef1f.PNG)

**Comment by Astrea123** [comment]
It is showing because you were using webapp in mobile .It will not show while you will use mobile package

**Comment by achille005** [comment]
Ok. Let me close this for now then
