### ISSUE TITLE
logo image on the browser tab

### ISSUE THREAD

**Issue by achille005** [achille005/JobApp#49]
See how every tab has their logo image, why our does?

![logo image on tab](https://user-images.githubusercontent.com/6147947/27503235-746208ec-5848-11e7-8472-f950f4eb3e29.png)

**Comment by Astrea123** [comment]
Please send logo for the tab. Currently we are using logo image, but it is not clear as shown in image. So, send small logo for this.

![image](https://user-images.githubusercontent.com/26182663/27830807-b0b50d80-60e5-11e7-9657-3c7228aa1717.png)

**Comment by achille005** [comment]
I have email a image, try that... Otherwise that is not a priority. Please fix the our feedback we gave you on UI - they want to use the UI in the advertising video
It may looks like i am obsessing but sometime it is the "little touch" to the app that catches people attention and the about the people behind the app.... e.g: you be using icon wherever possible, like error message
