### ISSUE TITLE
Challenge with the payment flow?

### ISSUE THREAD

**Issue by achille005** [achille005/JobApp#67]
I notice the flow is not going to payment screen yet. Are you having challenges with it?
Note: In the first release, we are not going to charge users. Do you know how to do free trial? I believe Stripe handle that. Correct?

**Comment by Astrea123** [comment]
Please try testing using (id- dsf@fdgfd.lk password-pra123@@), for this id payment has not been done. In this user can post maximum of 10 jobs. On clicking Contact job seeker, download resume, forward resume button on Talent/resume Alert tab he will be redirected to JobPrice page, there he can select type of plan he want to have after clicking continue he will be move to payment page. On payment page user can make payment using his bank account detail. 

If user has already made payment, then he can post number of jobs depending on the plan he had selected earlier. When he will click Contact job seeker, download resume, forward resume button on Talent/resume Alert tab then respective actions will be performed. 

This was the flow that we decided earlier, now if you want something else then tell us.

**Comment by achille005** [comment]
The flow is not changing but all i am saying is. It is a subscription model with 3 month free with no credit card required. After 3 month it becomes credit card required with re-occurring charges till user cancel.
Note: To my knowledge all this flow is a plug ins that Stripes should provide us. Please correct me if i am not correct.

**Comment by achille005** [comment]
moved to this payment Flow issue
